name: Sync Fork

on:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Pull updates
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git remote add upstream https://github.com/Simpsonpt/AppSecEzine.git
        git fetch upstream
        git merge upstream/main
        git push
